services:
  bot:
    image: ghcr.io/fashnel/spending-distributor-bot:latest
    container_name: telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HTTPS_PROXY=${PROXY_URL}
      - HTTP_PROXY=${PROXY_URL}
      - https_proxy=${PROXY_URL}
      - http_proxy=${PROXY_URL}
    volumes:
      - ./client_secret.json:/app/client_secret.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_DEBUG=true
      - DOCKER_API_VERSION=1.40
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup telegram_bot
